spring:
  application:
    name: dev

  # mariadb? ?? ??
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver

  # h2 console
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  sql:
    init:
      data-locations: classpath:data.sql
      mode: NEVER

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  web:
    resources:
      static-locations: classpath:/static/

